FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

# Set up Python 3.8
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update --fix-missing && \
    apt-get install -y \
                    python3-dev \
                    python3-pip \
                    git \
                    build-essential \
                    libgl1-mesa-dev \
                    mesa-utils \
                    libglu1-mesa-dev \
                    fontconfig \
                    libfreetype6-dev

RUN pip3 install --upgrade pip
RUN pip3 install PyOpenGL \
                 PyOpenGL_accelerate

RUN git clone https://github.com/f1tenth/f1tenth_gym.git
# checkout branch v1.0.0 and install requirements
RUN cd f1tenth_gym && \
    git checkout v1.0.0 && \
    pip3 install -e .
    
RUN git clone https://github.com/HyberionBrew/policy_eval.git
# checkout branch f110 and install requirements
RUN pip3 install tensorflow==2.12.0
RUN cd policy_eval && \
    git checkout f110 && \
    pip3 install -r requirements.txt
RUN pip3 install numba==0.55.2

#RUN pip3 install -r policy_eval/requirements.txt
RUN pip3 install protobuf==3.20
RUN mkdir -p /app/ws
RUN pip3 install gymnasium==0.28
# add export PYTHONPATH=$PYTHONPATH:/app/ws

COPY entrypoint.sh /entrypoint.sh
CMD ["/entrypoint.sh"]
#&& pip3 install -e ftg_agents/ && \
#            pip3 install -e f1tenth_orl_dataset/ "]