FROM ubuntu:20.04

ARG DEBIAN_FRONTEND="noninteractive"
ENV LIBGL_ALWAYS_INDIRECT=1
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}

ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

RUN apt-get update --fix-missing && \
    apt-get install -y \
                    python3-dev \
                    python3-pip \
                    git \
                    build-essential \
                    libgl1-mesa-dev \
                    mesa-utils \
                    libglu1-mesa-dev \
                    fontconfig \
                    libfreetype6-dev

RUN pip3 install --upgrade pip
RUN pip3 install PyOpenGL \
                 PyOpenGL_accelerate

RUN git clone https://github.com/f1tenth/f1tenth_gym.git
RUN cd f1tenth_gym && \
    pip3 install -e .
RUN git clone https://github.com/HyberionBrew/policy_eval.git
RUN pip3 install numba==0.55.2
RUN pip3 install -r policy_eval/requirements.txt
RUN pip3 install protobuf==3.20
RUN pip3 install tensorflow==2.12
RUN mkdir -p /app/ws
# add export PYTHONPATH=$PYTHONPATH:/app/ws
ENTRYPOINT ["/bin/bash"] 
#&& pip3 install -e ftg_agents/ && \
#            pip3 install -e f1tenth_orl_dataset/ "]